    // `include "config.v"


    `define MY_DECINFO_GRP_WIDTH    3
    `define MY_DECINFO_GRP_ALU      `MY_DECINFO_GRP_WIDTH'd0
    `define MY_DECINFO_GRP_AGU      `MY_DECINFO_GRP_WIDTH'd1
    `define MY_DECINFO_GRP_BJP      `MY_DECINFO_GRP_WIDTH'd2
    `define MY_DECINFO_GRP_CSR      `MY_DECINFO_GRP_WIDTH'd3
    `define MY_DECINFO_GRP_MULDIV   `MY_DECINFO_GRP_WIDTH'd4
    `define MY_DECINFO_GRP_NICE      `MY_DECINFO_GRP_WIDTH'd5
    `define MY_DECINFO_GRP_FPU      `MY_DECINFO_GRP_WIDTH'd6

    `define MY_DECINFO_GRP_FPU_WIDTH    2
    `define MY_DECINFO_GRP_FPU_FLSU     `MY_DECINFO_GRP_FPU_WIDTH'd0
    `define MY_DECINFO_GRP_FPU_FMAC     `MY_DECINFO_GRP_FPU_WIDTH'd1
    `define MY_DECINFO_GRP_FPU_FDIV     `MY_DECINFO_GRP_FPU_WIDTH'd2
    `define MY_DECINFO_GRP_FPU_FMIS     `MY_DECINFO_GRP_FPU_WIDTH'd3

        `define MY_DECINFO_GRP_LSB  0
        `define MY_DECINFO_GRP_MSB  (`MY_DECINFO_GRP_LSB+`MY_DECINFO_GRP_WIDTH-1)
    `define MY_DECINFO_GRP          `MY_DECINFO_GRP_MSB:`MY_DECINFO_GRP_LSB
        `define MY_DECINFO_RV32_LSB  (`MY_DECINFO_GRP_MSB+1)
        `define MY_DECINFO_RV32_MSB  (`MY_DECINFO_RV32_LSB+1-1)
    `define MY_DECINFO_RV32          `MY_DECINFO_RV32_MSB:`MY_DECINFO_RV32_LSB

    `define MY_DECINFO_SUBDECINFO_LSB    (`MY_DECINFO_RV32_MSB+1)

    // ALU group
        `define MY_DECINFO_ALU_ADD_LSB    `MY_DECINFO_SUBDECINFO_LSB
        `define MY_DECINFO_ALU_ADD_MSB    (`MY_DECINFO_ALU_ADD_LSB+1-1)
    `define MY_DECINFO_ALU_ADD    `MY_DECINFO_ALU_ADD_MSB :`MY_DECINFO_ALU_ADD_LSB 
        `define MY_DECINFO_ALU_SUB_LSB    (`MY_DECINFO_ALU_ADD_MSB+1)
        `define MY_DECINFO_ALU_SUB_MSB    (`MY_DECINFO_ALU_SUB_LSB+1-1)
    `define MY_DECINFO_ALU_SUB    `MY_DECINFO_ALU_SUB_MSB :`MY_DECINFO_ALU_SUB_LSB 
        `define MY_DECINFO_ALU_XOR_LSB    (`MY_DECINFO_ALU_SUB_MSB+1)
        `define MY_DECINFO_ALU_XOR_MSB    (`MY_DECINFO_ALU_XOR_LSB+1-1)
    `define MY_DECINFO_ALU_XOR    `MY_DECINFO_ALU_XOR_MSB :`MY_DECINFO_ALU_XOR_LSB 
        `define MY_DECINFO_ALU_SLL_LSB    (`MY_DECINFO_ALU_XOR_MSB+1)
        `define MY_DECINFO_ALU_SLL_MSB    (`MY_DECINFO_ALU_SLL_LSB+1-1)
    `define MY_DECINFO_ALU_SLL    `MY_DECINFO_ALU_SLL_MSB :`MY_DECINFO_ALU_SLL_LSB 
        `define MY_DECINFO_ALU_SRL_LSB    (`MY_DECINFO_ALU_SLL_MSB+1)
        `define MY_DECINFO_ALU_SRL_MSB    (`MY_DECINFO_ALU_SRL_LSB+1-1)
    `define MY_DECINFO_ALU_SRL    `MY_DECINFO_ALU_SRL_MSB :`MY_DECINFO_ALU_SRL_LSB 
        `define MY_DECINFO_ALU_SRA_LSB    (`MY_DECINFO_ALU_SRL_MSB+1)
        `define MY_DECINFO_ALU_SRA_MSB    (`MY_DECINFO_ALU_SRA_LSB+1-1)
    `define MY_DECINFO_ALU_SRA    `MY_DECINFO_ALU_SRA_MSB :`MY_DECINFO_ALU_SRA_LSB 
        `define MY_DECINFO_ALU_OR_LSB    (`MY_DECINFO_ALU_SRA_MSB+1)
        `define MY_DECINFO_ALU_OR_MSB    (`MY_DECINFO_ALU_OR_LSB+1-1)
    `define MY_DECINFO_ALU_OR     `MY_DECINFO_ALU_OR_MSB  :`MY_DECINFO_ALU_OR_LSB  
        `define MY_DECINFO_ALU_AND_LSB    (`MY_DECINFO_ALU_OR_MSB+1)
        `define MY_DECINFO_ALU_AND_MSB    (`MY_DECINFO_ALU_AND_LSB+1-1)
    `define MY_DECINFO_ALU_AND    `MY_DECINFO_ALU_AND_MSB :`MY_DECINFO_ALU_AND_LSB 
        `define MY_DECINFO_ALU_SLT_LSB    (`MY_DECINFO_ALU_AND_MSB+1)
        `define MY_DECINFO_ALU_SLT_MSB    (`MY_DECINFO_ALU_SLT_LSB+1-1)
    `define MY_DECINFO_ALU_SLT    `MY_DECINFO_ALU_SLT_MSB :`MY_DECINFO_ALU_SLT_LSB 
        `define MY_DECINFO_ALU_SLTU_LSB    (`MY_DECINFO_ALU_SLT_MSB+1)
        `define MY_DECINFO_ALU_SLTU_MSB    (`MY_DECINFO_ALU_SLTU_LSB+1-1)
    `define MY_DECINFO_ALU_SLTU   `MY_DECINFO_ALU_SLTU_MSB:`MY_DECINFO_ALU_SLTU_LSB
        `define MY_DECINFO_ALU_LUI_LSB    (`MY_DECINFO_ALU_SLTU_MSB+1)
        `define MY_DECINFO_ALU_LUI_MSB    (`MY_DECINFO_ALU_LUI_LSB+1-1)
    `define MY_DECINFO_ALU_LUI    `MY_DECINFO_ALU_LUI_MSB :`MY_DECINFO_ALU_LUI_LSB 
        `define MY_DECINFO_ALU_OP2IMM_LSB    (`MY_DECINFO_ALU_LUI_MSB+1)
        `define MY_DECINFO_ALU_OP2IMM_MSB    (`MY_DECINFO_ALU_OP2IMM_LSB+1-1)
    `define MY_DECINFO_ALU_OP2IMM    `MY_DECINFO_ALU_OP2IMM_MSB :`MY_DECINFO_ALU_OP2IMM_LSB 
        `define MY_DECINFO_ALU_OP1PC_LSB    (`MY_DECINFO_ALU_OP2IMM_MSB+1)
        `define MY_DECINFO_ALU_OP1PC_MSB    (`MY_DECINFO_ALU_OP1PC_LSB+1-1)
    `define MY_DECINFO_ALU_OP1PC    `MY_DECINFO_ALU_OP1PC_MSB :`MY_DECINFO_ALU_OP1PC_LSB 
        `define MY_DECINFO_ALU_RESW_LSB    (`MY_DECINFO_ALU_OP1PC_MSB+1)
        `define MY_DECINFO_ALU_RESW_MSB    (`MY_DECINFO_ALU_RESW_LSB+1-1)
    `define MY_DECINFO_ALU_RESW    `MY_DECINFO_ALU_RESW_MSB :`MY_DECINFO_ALU_RESW_LSB 
        `define MY_DECINFO_ALU_NOP_LSB    (`MY_DECINFO_ALU_RESW_MSB+1)
        `define MY_DECINFO_ALU_NOP_MSB    (`MY_DECINFO_ALU_NOP_LSB+1-1)
    `define MY_DECINFO_ALU_NOP    `MY_DECINFO_ALU_NOP_MSB :`MY_DECINFO_ALU_NOP_LSB 
        `define MY_DECINFO_ALU_ECAL_LSB  (`MY_DECINFO_ALU_NOP_MSB+1)
        `define MY_DECINFO_ALU_ECAL_MSB  (`MY_DECINFO_ALU_ECAL_LSB+1-1)
    `define MY_DECINFO_ALU_ECAL   `MY_DECINFO_ALU_ECAL_MSB:`MY_DECINFO_ALU_ECAL_LSB 
        `define MY_DECINFO_ALU_EBRK_LSB  (`MY_DECINFO_ALU_ECAL_MSB+1)
        `define MY_DECINFO_ALU_EBRK_MSB  (`MY_DECINFO_ALU_EBRK_LSB+1-1)
    `define MY_DECINFO_ALU_EBRK   `MY_DECINFO_ALU_EBRK_MSB:`MY_DECINFO_ALU_EBRK_LSB 
        `define MY_DECINFO_ALU_WFI_LSB  (`MY_DECINFO_ALU_EBRK_MSB+1)
        `define MY_DECINFO_ALU_WFI_MSB  (`MY_DECINFO_ALU_WFI_LSB+1-1)
    `define MY_DECINFO_ALU_WFI   `MY_DECINFO_ALU_WFI_MSB:`MY_DECINFO_ALU_WFI_LSB 

    `define MY_DECINFO_ALU_WIDTH    (`MY_DECINFO_ALU_WFI_MSB+1)

    //AGU group
        `define MY_DECINFO_AGU_LOAD_LSB      `MY_DECINFO_SUBDECINFO_LSB
        `define MY_DECINFO_AGU_LOAD_MSB      (`MY_DECINFO_AGU_LOAD_LSB+1-1)   
    `define MY_DECINFO_AGU_LOAD      `MY_DECINFO_AGU_LOAD_MSB   :`MY_DECINFO_AGU_LOAD_LSB   
        `define MY_DECINFO_AGU_STORE_LSB      (`MY_DECINFO_AGU_LOAD_MSB+1)
        `define MY_DECINFO_AGU_STORE_MSB      (`MY_DECINFO_AGU_STORE_LSB+1-1)   
    `define MY_DECINFO_AGU_STORE     `MY_DECINFO_AGU_STORE_MSB  :`MY_DECINFO_AGU_STORE_LSB  
        `define MY_DECINFO_AGU_SIZE_LSB      (`MY_DECINFO_AGU_STORE_MSB+1)
        `define MY_DECINFO_AGU_SIZE_MSB      (`MY_DECINFO_AGU_SIZE_LSB+2-1)   
    `define MY_DECINFO_AGU_SIZE      `MY_DECINFO_AGU_SIZE_MSB   :`MY_DECINFO_AGU_SIZE_LSB   
        `define MY_DECINFO_AGU_USIGN_LSB      (`MY_DECINFO_AGU_SIZE_MSB+1)
        `define MY_DECINFO_AGU_USIGN_MSB      (`MY_DECINFO_AGU_USIGN_LSB+1-1)   
    `define MY_DECINFO_AGU_USIGN     `MY_DECINFO_AGU_USIGN_MSB  :`MY_DECINFO_AGU_USIGN_LSB  
        `define MY_DECINFO_AGU_EXCL_LSB      (`MY_DECINFO_AGU_USIGN_MSB+1)
        `define MY_DECINFO_AGU_EXCL_MSB      (`MY_DECINFO_AGU_EXCL_LSB+1-1)   
    `define MY_DECINFO_AGU_EXCL      `MY_DECINFO_AGU_EXCL_MSB   :`MY_DECINFO_AGU_EXCL_LSB   
        `define MY_DECINFO_AGU_AMO_LSB      (`MY_DECINFO_AGU_EXCL_MSB+1)
        `define MY_DECINFO_AGU_AMO_MSB      (`MY_DECINFO_AGU_AMO_LSB+1-1)   
    `define MY_DECINFO_AGU_AMO       `MY_DECINFO_AGU_AMO_MSB    :`MY_DECINFO_AGU_AMO_LSB    
        `define MY_DECINFO_AGU_AMOSWAP_LSB      (`MY_DECINFO_AGU_AMO_MSB+1)
        `define MY_DECINFO_AGU_AMOSWAP_MSB      (`MY_DECINFO_AGU_AMOSWAP_LSB+1-1)   
    `define MY_DECINFO_AGU_AMOSWAP   `MY_DECINFO_AGU_AMOSWAP_MSB:`MY_DECINFO_AGU_AMOSWAP_LSB
        `define MY_DECINFO_AGU_AMOADD_LSB      (`MY_DECINFO_AGU_AMOSWAP_MSB+1)
        `define MY_DECINFO_AGU_AMOADD_MSB      (`MY_DECINFO_AGU_AMOADD_LSB+1-1)   
    `define MY_DECINFO_AGU_AMOADD    `MY_DECINFO_AGU_AMOADD_MSB :`MY_DECINFO_AGU_AMOADD_LSB 
        `define MY_DECINFO_AGU_AMOAND_LSB      (`MY_DECINFO_AGU_AMOADD_MSB+1)
        `define MY_DECINFO_AGU_AMOAND_MSB      (`MY_DECINFO_AGU_AMOAND_LSB+1-1)   
    `define MY_DECINFO_AGU_AMOAND    `MY_DECINFO_AGU_AMOAND_MSB :`MY_DECINFO_AGU_AMOAND_LSB 
        `define MY_DECINFO_AGU_AMOOR_LSB      (`MY_DECINFO_AGU_AMOAND_MSB+1)
        `define MY_DECINFO_AGU_AMOOR_MSB      (`MY_DECINFO_AGU_AMOOR_LSB+1-1)   
    `define MY_DECINFO_AGU_AMOOR     `MY_DECINFO_AGU_AMOOR_MSB  :`MY_DECINFO_AGU_AMOOR_LSB  
        `define MY_DECINFO_AGU_AMOXOR_LSB      (`MY_DECINFO_AGU_AMOOR_MSB+1)
        `define MY_DECINFO_AGU_AMOXOR_MSB      (`MY_DECINFO_AGU_AMOXOR_LSB+1-1)   
    `define MY_DECINFO_AGU_AMOXOR    `MY_DECINFO_AGU_AMOXOR_MSB :`MY_DECINFO_AGU_AMOXOR_LSB 
        `define MY_DECINFO_AGU_AMOMAX_LSB      (`MY_DECINFO_AGU_AMOXOR_MSB+1)
        `define MY_DECINFO_AGU_AMOMAX_MSB      (`MY_DECINFO_AGU_AMOMAX_LSB+1-1)   
    `define MY_DECINFO_AGU_AMOMAX    `MY_DECINFO_AGU_AMOMAX_MSB :`MY_DECINFO_AGU_AMOMAX_LSB 
        `define MY_DECINFO_AGU_AMOMIN_LSB      (`MY_DECINFO_AGU_AMOMAX_MSB+1)
        `define MY_DECINFO_AGU_AMOMIN_MSB      (`MY_DECINFO_AGU_AMOMIN_LSB+1-1)   
    `define MY_DECINFO_AGU_AMOMIN    `MY_DECINFO_AGU_AMOMIN_MSB :`MY_DECINFO_AGU_AMOMIN_LSB 
        `define MY_DECINFO_AGU_AMOMAXU_LSB      (`MY_DECINFO_AGU_AMOMIN_MSB+1)
        `define MY_DECINFO_AGU_AMOMAXU_MSB      (`MY_DECINFO_AGU_AMOMAXU_LSB+1-1)   
    `define MY_DECINFO_AGU_AMOMAXU   `MY_DECINFO_AGU_AMOMAXU_MSB:`MY_DECINFO_AGU_AMOMAXU_LSB
        `define MY_DECINFO_AGU_AMOMINU_LSB      (`MY_DECINFO_AGU_AMOMAXU_MSB+1)
        `define MY_DECINFO_AGU_AMOMINU_MSB      (`MY_DECINFO_AGU_AMOMINU_LSB+1-1)   
    `define MY_DECINFO_AGU_AMOMINU   `MY_DECINFO_AGU_AMOMINU_MSB:`MY_DECINFO_AGU_AMOMINU_LSB
        `define MY_DECINFO_AGU_OP2IMM_LSB      (`MY_DECINFO_AGU_AMOMINU_MSB+1)
        `define MY_DECINFO_AGU_OP2IMM_MSB      (`MY_DECINFO_AGU_OP2IMM_LSB+1-1)   
    `define MY_DECINFO_AGU_OP2IMM   `MY_DECINFO_AGU_OP2IMM_MSB:`MY_DECINFO_AGU_OP2IMM_LSB

    `define MY_DECINFO_AGU_WIDTH    (`MY_DECINFO_AGU_OP2IMM_MSB+1)

    // Bxx group
        `define MY_DECINFO_BJP_JAL_LSB `MY_DECINFO_SUBDECINFO_LSB
        `define MY_DECINFO_BJP_JAL_MSB (`MY_DECINFO_BJP_JAL_LSB+1-1)
    `define MY_DECINFO_BJP_JAL   `MY_DECINFO_BJP_JAL_MSB :`MY_DECINFO_BJP_JAL_LSB 
        `define MY_DECINFO_BJP_JALR_LSB (`MY_DECINFO_BJP_JAL_MSB +1 )
        `define MY_DECINFO_BJP_JALR_MSB (`MY_DECINFO_BJP_JALR_LSB+1-1)
    `define MY_DECINFO_BJP_JALR   `MY_DECINFO_BJP_JALR_MSB :`MY_DECINFO_BJP_JALR_LSB 
        `define MY_DECINFO_BJP_BPRDT_LSB (`MY_DECINFO_BJP_JALR_MSB+1)
        `define MY_DECINFO_BJP_BPRDT_MSB (`MY_DECINFO_BJP_BPRDT_LSB+1-1)
    `define MY_DECINFO_BJP_BPRDT  `MY_DECINFO_BJP_BPRDT_MSB:`MY_DECINFO_BJP_BPRDT_LSB
        `define MY_DECINFO_BJP_BEQ_LSB (`MY_DECINFO_BJP_BPRDT_MSB+1)
        `define MY_DECINFO_BJP_BEQ_MSB (`MY_DECINFO_BJP_BEQ_LSB+1-1)
    `define MY_DECINFO_BJP_BEQ    `MY_DECINFO_BJP_BEQ_MSB  :`MY_DECINFO_BJP_BEQ_LSB  
        `define MY_DECINFO_BJP_BNE_LSB (`MY_DECINFO_BJP_BEQ_MSB+1)
        `define MY_DECINFO_BJP_BNE_MSB (`MY_DECINFO_BJP_BNE_LSB+1-1)
    `define MY_DECINFO_BJP_BNE    `MY_DECINFO_BJP_BNE_MSB  :`MY_DECINFO_BJP_BNE_LSB  
        `define MY_DECINFO_BJP_BLT_LSB (`MY_DECINFO_BJP_BNE_MSB+1)
        `define MY_DECINFO_BJP_BLT_MSB (`MY_DECINFO_BJP_BLT_LSB+1-1)
    `define MY_DECINFO_BJP_BLT    `MY_DECINFO_BJP_BLT_MSB  :`MY_DECINFO_BJP_BLT_LSB  
        `define MY_DECINFO_BJP_BGT_LSB (`MY_DECINFO_BJP_BLT_MSB+1)
        `define MY_DECINFO_BJP_BGT_MSB (`MY_DECINFO_BJP_BGT_LSB+1-1)
    `define MY_DECINFO_BJP_BGT    `MY_DECINFO_BJP_BGT_MSB  :`MY_DECINFO_BJP_BGT_LSB  
        `define MY_DECINFO_BJP_BLTU_LSB (`MY_DECINFO_BJP_BGT_MSB+1)
        `define MY_DECINFO_BJP_BLTU_MSB (`MY_DECINFO_BJP_BLTU_LSB+1-1)
    `define MY_DECINFO_BJP_BLTU   `MY_DECINFO_BJP_BLTU_MSB :`MY_DECINFO_BJP_BLTU_LSB 
        `define MY_DECINFO_BJP_BGTU_LSB (`MY_DECINFO_BJP_BLTU_MSB+1)
        `define MY_DECINFO_BJP_BGTU_MSB (`MY_DECINFO_BJP_BGTU_LSB+1-1)
    `define MY_DECINFO_BJP_BGTU   `MY_DECINFO_BJP_BGTU_MSB :`MY_DECINFO_BJP_BGTU_LSB 
        `define MY_DECINFO_BJP_BXX_LSB  (`MY_DECINFO_BJP_BGTU_MSB+1)
        `define MY_DECINFO_BJP_BXX_MSB  (`MY_DECINFO_BJP_BXX_LSB+1-1)
    `define MY_DECINFO_BJP_BXX    `MY_DECINFO_BJP_BXX_MSB :`MY_DECINFO_BJP_BXX_LSB
        `define MY_DECINFO_BJP_MRET_LSB  (`MY_DECINFO_BJP_BXX_MSB+1)
        `define MY_DECINFO_BJP_MRET_MSB  (`MY_DECINFO_BJP_MRET_LSB+1-1)
    `define MY_DECINFO_BJP_MRET    `MY_DECINFO_BJP_MRET_MSB :`MY_DECINFO_BJP_MRET_LSB
        `define MY_DECINFO_BJP_DRET_LSB  (`MY_DECINFO_BJP_MRET_MSB+1)
        `define MY_DECINFO_BJP_DRET_MSB  (`MY_DECINFO_BJP_DRET_LSB+1-1)
    `define MY_DECINFO_BJP_DRET    `MY_DECINFO_BJP_DRET_MSB :`MY_DECINFO_BJP_DRET_LSB
        `define MY_DECINFO_BJP_FENCE_LSB  (`MY_DECINFO_BJP_DRET_MSB+1)
        `define MY_DECINFO_BJP_FENCE_MSB  (`MY_DECINFO_BJP_FENCE_LSB+1-1)
    `define MY_DECINFO_BJP_FENCE    `MY_DECINFO_BJP_FENCE_MSB :`MY_DECINFO_BJP_FENCE_LSB
        `define MY_DECINFO_BJP_FENCEI_LSB  (`MY_DECINFO_BJP_FENCE_MSB+1)
        `define MY_DECINFO_BJP_FENCEI_MSB  (`MY_DECINFO_BJP_FENCEI_LSB+1-1)
    `define MY_DECINFO_BJP_FENCEI    `MY_DECINFO_BJP_FENCEI_MSB :`MY_DECINFO_BJP_FENCEI_LSB

    `define MY_DECINFO_BJP_WIDTH  (`MY_DECINFO_BJP_FENCEI_MSB+1)


    // CSR group
        `define MY_DECINFO_CSR_CSRRW_LSB   `MY_DECINFO_SUBDECINFO_LSB
        `define MY_DECINFO_CSR_CSRRW_MSB   (`MY_DECINFO_CSR_CSRRW_LSB+1-1)    
    `define MY_DECINFO_CSR_CSRRW   `MY_DECINFO_CSR_CSRRW_MSB:`MY_DECINFO_CSR_CSRRW_LSB    
        `define MY_DECINFO_CSR_CSRRS_LSB   (`MY_DECINFO_CSR_CSRRW_MSB+1)
        `define MY_DECINFO_CSR_CSRRS_MSB   (`MY_DECINFO_CSR_CSRRS_LSB+1-1)    
    `define MY_DECINFO_CSR_CSRRS   `MY_DECINFO_CSR_CSRRS_MSB:`MY_DECINFO_CSR_CSRRS_LSB 
        `define MY_DECINFO_CSR_CSRRC_LSB   (`MY_DECINFO_CSR_CSRRS_MSB+1)
        `define MY_DECINFO_CSR_CSRRC_MSB   (`MY_DECINFO_CSR_CSRRC_LSB+1-1)    
    `define MY_DECINFO_CSR_CSRRC   `MY_DECINFO_CSR_CSRRC_MSB:`MY_DECINFO_CSR_CSRRC_LSB 
        `define MY_DECINFO_CSR_RS1IMM_LSB  (`MY_DECINFO_CSR_CSRRC_MSB+1)
        `define MY_DECINFO_CSR_RS1IMM_MSB   (`MY_DECINFO_CSR_RS1IMM_LSB+1-1)    
    `define MY_DECINFO_CSR_RS1IMM  `MY_DECINFO_CSR_RS1IMM_MSB:`MY_DECINFO_CSR_RS1IMM_LSB
        `define MY_DECINFO_CSR_ZIMMM_LSB   (`MY_DECINFO_CSR_RS1IMM_MSB+1)
        `define MY_DECINFO_CSR_ZIMMM_MSB   (`MY_DECINFO_CSR_ZIMMM_LSB+5-1)    
    `define MY_DECINFO_CSR_ZIMMM   `MY_DECINFO_CSR_ZIMMM_MSB:`MY_DECINFO_CSR_ZIMMM_LSB 
        `define MY_DECINFO_CSR_RS1IS0_LSB  (`MY_DECINFO_CSR_ZIMMM_MSB+1)
        `define MY_DECINFO_CSR_RS1IS0_MSB  (`MY_DECINFO_CSR_RS1IS0_LSB+1-1)    
    `define MY_DECINFO_CSR_RS1IS0  `MY_DECINFO_CSR_RS1IS0_MSB:`MY_DECINFO_CSR_RS1IS0_LSB
        `define MY_DECINFO_CSR_CSRIDX_LSB  (`MY_DECINFO_CSR_RS1IS0_MSB+1)
        `define MY_DECINFO_CSR_CSRIDX_MSB  (`MY_DECINFO_CSR_CSRIDX_LSB+12-1)    
    `define MY_DECINFO_CSR_CSRIDX  `MY_DECINFO_CSR_CSRIDX_MSB:`MY_DECINFO_CSR_CSRIDX_LSB

    `define MY_DECINFO_CSR_WIDTH  (`MY_DECINFO_CSR_CSRIDX_MSB+1)

    // NICE group
        `define MY_DECINFO_NICE_INSTR_LSB   `MY_DECINFO_SUBDECINFO_LSB
        `define MY_DECINFO_NICE_INSTR_MSB   (`MY_DECINFO_NICE_INSTR_LSB+27-1)    
    `define MY_DECINFO_NICE_INSTR   `MY_DECINFO_NICE_INSTR_MSB:`MY_DECINFO_NICE_INSTR_LSB    

    `define MY_DECINFO_NICE_WIDTH  (`MY_DECINFO_NICE_INSTR_MSB+1)

        `define MY_DECINFO_FPU_GRP_LSB   `MY_DECINFO_SUBDECINFO_LSB
        `define MY_DECINFO_FPU_GRP_MSB   (`MY_DECINFO_FPU_GRP_LSB+`MY_DECINFO_GRP_FPU_WIDTH-1)    
    `define MY_DECINFO_FPU_GRP   `MY_DECINFO_FPU_GRP_MSB:`MY_DECINFO_FPU_GRP_LSB    
        `define MY_DECINFO_FPU_RM_LSB   (`MY_DECINFO_FPU_GRP_MSB+1)
        `define MY_DECINFO_FPU_RM_MSB   (`MY_DECINFO_FPU_RM_LSB+3-1)    
    `define MY_DECINFO_FPU_RM   `MY_DECINFO_FPU_RM_MSB:`MY_DECINFO_FPU_RM_LSB    
        `define MY_DECINFO_FPU_USERM_LSB   (`MY_DECINFO_FPU_RM_MSB+1)
        `define MY_DECINFO_FPU_USERM_MSB   (`MY_DECINFO_FPU_USERM_LSB+1-1)    
    `define MY_DECINFO_FPU_USERM   `MY_DECINFO_FPU_USERM_MSB:`MY_DECINFO_FPU_USERM_LSB    

    // FLSU group
        `define MY_DECINFO_FLSU_LOAD_LSB   (`MY_DECINFO_FPU_USERM_MSB+1)
        `define MY_DECINFO_FLSU_LOAD_MSB   (`MY_DECINFO_FLSU_LOAD_LSB+1-1)    
    `define MY_DECINFO_FLSU_LOAD   `MY_DECINFO_FLSU_LOAD_MSB:`MY_DECINFO_FLSU_LOAD_LSB 
        `define MY_DECINFO_FLSU_STORE_LSB   (`MY_DECINFO_FLSU_LOAD_MSB+1)
        `define MY_DECINFO_FLSU_STORE_MSB   (`MY_DECINFO_FLSU_STORE_LSB+1-1)    
    `define MY_DECINFO_FLSU_STORE   `MY_DECINFO_FLSU_STORE_MSB:`MY_DECINFO_FLSU_STORE_LSB 
        `define MY_DECINFO_FLSU_DOUBLE_LSB  (`MY_DECINFO_FLSU_STORE_MSB+1)
        `define MY_DECINFO_FLSU_DOUBLE_MSB   (`MY_DECINFO_FLSU_DOUBLE_LSB+1-1)    
    `define MY_DECINFO_FLSU_DOUBLE  `MY_DECINFO_FLSU_DOUBLE_MSB:`MY_DECINFO_FLSU_DOUBLE_LSB
        `define MY_DECINFO_FLSU_OP2IMM_LSB   (`MY_DECINFO_FLSU_DOUBLE_MSB+1)
        `define MY_DECINFO_FLSU_OP2IMM_MSB   (`MY_DECINFO_FLSU_OP2IMM_LSB+1-1)    
    `define MY_DECINFO_FLSU_OP2IMM   `MY_DECINFO_FLSU_OP2IMM_MSB:`MY_DECINFO_FLSU_OP2IMM_LSB 

    `define MY_DECINFO_FLSU_WIDTH  (`MY_DECINFO_FLSU_OP2IMM_MSB+1)

    // FDIV group
        `define MY_DECINFO_FDIV_DIV_LSB   (`MY_DECINFO_FPU_USERM_MSB+1)
        `define MY_DECINFO_FDIV_DIV_MSB   (`MY_DECINFO_FDIV_DIV_LSB+1-1)    
    `define MY_DECINFO_FDIV_DIV   `MY_DECINFO_FDIV_DIV_MSB:`MY_DECINFO_FDIV_DIV_LSB 
        `define MY_DECINFO_FDIV_SQRT_LSB   (`MY_DECINFO_FDIV_DIV_MSB+1)
        `define MY_DECINFO_FDIV_SQRT_MSB   (`MY_DECINFO_FDIV_SQRT_LSB+1-1)    
    `define MY_DECINFO_FDIV_SQRT   `MY_DECINFO_FDIV_SQRT_MSB:`MY_DECINFO_FDIV_SQRT_LSB 
        `define MY_DECINFO_FDIV_DOUBLE_LSB  (`MY_DECINFO_FDIV_SQRT_MSB+1)
        `define MY_DECINFO_FDIV_DOUBLE_MSB   (`MY_DECINFO_FDIV_DOUBLE_LSB+1-1)    
    `define MY_DECINFO_FDIV_DOUBLE  `MY_DECINFO_FDIV_DOUBLE_MSB:`MY_DECINFO_FDIV_DOUBLE_LSB

    `define MY_DECINFO_FDIV_WIDTH  (`MY_DECINFO_FDIV_DOUBLE_MSB+1)

    // FMIS group
        `define MY_DECINFO_FMIS_FSGNJ_LSB   (`MY_DECINFO_FPU_USERM_MSB+1)
        `define MY_DECINFO_FMIS_FSGNJ_MSB   (`MY_DECINFO_FMIS_FSGNJ_LSB+1-1)    
    `define MY_DECINFO_FMIS_FSGNJ   `MY_DECINFO_FMIS_FSGNJ_MSB:`MY_DECINFO_FMIS_FSGNJ_LSB 
        `define MY_DECINFO_FMIS_FSGNJN_LSB   (`MY_DECINFO_FMIS_FSGNJ_MSB+1)
        `define MY_DECINFO_FMIS_FSGNJN_MSB   (`MY_DECINFO_FMIS_FSGNJN_LSB+1-1)    
    `define MY_DECINFO_FMIS_FSGNJN   `MY_DECINFO_FMIS_FSGNJN_MSB:`MY_DECINFO_FMIS_FSGNJN_LSB 
        `define MY_DECINFO_FMIS_FSGNJX_LSB  (`MY_DECINFO_FMIS_FSGNJN_MSB+1)
        `define MY_DECINFO_FMIS_FSGNJX_MSB   (`MY_DECINFO_FMIS_FSGNJX_LSB+1-1)    
    `define MY_DECINFO_FMIS_FSGNJX  `MY_DECINFO_FMIS_FSGNJX_MSB:`MY_DECINFO_FMIS_FSGNJX_LSB
        `define MY_DECINFO_FMIS_FMVXW_LSB  (`MY_DECINFO_FMIS_FSGNJX_MSB+1)
        `define MY_DECINFO_FMIS_FMVXW_MSB   (`MY_DECINFO_FMIS_FMVXW_LSB+1-1)    
    `define MY_DECINFO_FMIS_FMVXW  `MY_DECINFO_FMIS_FMVXW_MSB:`MY_DECINFO_FMIS_FMVXW_LSB
        `define MY_DECINFO_FMIS_FCLASS_LSB  (`MY_DECINFO_FMIS_FMVXW_MSB+1)
        `define MY_DECINFO_FMIS_FCLASS_MSB   (`MY_DECINFO_FMIS_FCLASS_LSB+1-1)    
    `define MY_DECINFO_FMIS_FCLASS  `MY_DECINFO_FMIS_FCLASS_MSB:`MY_DECINFO_FMIS_FCLASS_LSB
        `define MY_DECINFO_FMIS_FMVWX_LSB  (`MY_DECINFO_FMIS_FCLASS_MSB+1)
        `define MY_DECINFO_FMIS_FMVWX_MSB   (`MY_DECINFO_FMIS_FMVWX_LSB+1-1)    
    `define MY_DECINFO_FMIS_FMVWX  `MY_DECINFO_FMIS_FMVWX_MSB:`MY_DECINFO_FMIS_FMVWX_LSB
        `define MY_DECINFO_FMIS_CVTWS_LSB  (`MY_DECINFO_FMIS_FMVWX_MSB+1)
        `define MY_DECINFO_FMIS_CVTWS_MSB   (`MY_DECINFO_FMIS_CVTWS_LSB+1-1)    
    `define MY_DECINFO_FMIS_CVTWS  `MY_DECINFO_FMIS_CVTWS_MSB:`MY_DECINFO_FMIS_CVTWS_LSB
        `define MY_DECINFO_FMIS_CVTWUS_LSB  (`MY_DECINFO_FMIS_CVTWS_MSB+1)
        `define MY_DECINFO_FMIS_CVTWUS_MSB   (`MY_DECINFO_FMIS_CVTWUS_LSB+1-1)    
    `define MY_DECINFO_FMIS_CVTWUS  `MY_DECINFO_FMIS_CVTWUS_MSB:`MY_DECINFO_FMIS_CVTWUS_LSB
        `define MY_DECINFO_FMIS_CVTSW_LSB  (`MY_DECINFO_FMIS_CVTWUS_MSB+1)
        `define MY_DECINFO_FMIS_CVTSW_MSB   (`MY_DECINFO_FMIS_CVTSW_LSB+1-1)    
    `define MY_DECINFO_FMIS_CVTSW  `MY_DECINFO_FMIS_CVTSW_MSB:`MY_DECINFO_FMIS_CVTSW_LSB
        `define MY_DECINFO_FMIS_CVTSWU_LSB  (`MY_DECINFO_FMIS_CVTSW_MSB+1)
        `define MY_DECINFO_FMIS_CVTSWU_MSB   (`MY_DECINFO_FMIS_CVTSWU_LSB+1-1)    
    `define MY_DECINFO_FMIS_CVTSWU  `MY_DECINFO_FMIS_CVTSWU_MSB:`MY_DECINFO_FMIS_CVTSWU_LSB
        `define MY_DECINFO_FMIS_CVTSD_LSB  (`MY_DECINFO_FMIS_CVTSWU_MSB+1)
        `define MY_DECINFO_FMIS_CVTSD_MSB   (`MY_DECINFO_FMIS_CVTSD_LSB+1-1)    
    `define MY_DECINFO_FMIS_CVTSD  `MY_DECINFO_FMIS_CVTSD_MSB:`MY_DECINFO_FMIS_CVTSD_LSB
        `define MY_DECINFO_FMIS_CVTDS_LSB  (`MY_DECINFO_FMIS_CVTSD_MSB+1)
        `define MY_DECINFO_FMIS_CVTDS_MSB   (`MY_DECINFO_FMIS_CVTDS_LSB+1-1)    
    `define MY_DECINFO_FMIS_CVTDS  `MY_DECINFO_FMIS_CVTDS_MSB:`MY_DECINFO_FMIS_CVTDS_LSB
        `define MY_DECINFO_FMIS_CVTWD_LSB  (`MY_DECINFO_FMIS_CVTDS_MSB+1)
        `define MY_DECINFO_FMIS_CVTWD_MSB   (`MY_DECINFO_FMIS_CVTWD_LSB+1-1)    
    `define MY_DECINFO_FMIS_CVTWD  `MY_DECINFO_FMIS_CVTWD_MSB:`MY_DECINFO_FMIS_CVTWD_LSB
        `define MY_DECINFO_FMIS_CVTWUD_LSB  (`MY_DECINFO_FMIS_CVTWD_MSB+1)
        `define MY_DECINFO_FMIS_CVTWUD_MSB   (`MY_DECINFO_FMIS_CVTWUD_LSB+1-1)    
    `define MY_DECINFO_FMIS_CVTWUD  `MY_DECINFO_FMIS_CVTWUD_MSB:`MY_DECINFO_FMIS_CVTWUD_LSB
        `define MY_DECINFO_FMIS_CVTDW_LSB  (`MY_DECINFO_FMIS_CVTWUD_MSB+1)
        `define MY_DECINFO_FMIS_CVTDW_MSB   (`MY_DECINFO_FMIS_CVTDW_LSB+1-1)    
    `define MY_DECINFO_FMIS_CVTDW  `MY_DECINFO_FMIS_CVTDW_MSB:`MY_DECINFO_FMIS_CVTDW_LSB
        `define MY_DECINFO_FMIS_CVTDWU_LSB  (`MY_DECINFO_FMIS_CVTDW_MSB+1)
        `define MY_DECINFO_FMIS_CVTDWU_MSB   (`MY_DECINFO_FMIS_CVTDWU_LSB+1-1)    
    `define MY_DECINFO_FMIS_CVTDWU  `MY_DECINFO_FMIS_CVTDWU_MSB:`MY_DECINFO_FMIS_CVTDWU_LSB
        `define MY_DECINFO_FMIS_DOUBLE_LSB  (`MY_DECINFO_FMIS_CVTDWU_MSB+1)
        `define MY_DECINFO_FMIS_DOUBLE_MSB   (`MY_DECINFO_FMIS_DOUBLE_LSB+1-1)    
    `define MY_DECINFO_FMIS_DOUBLE  `MY_DECINFO_FMIS_DOUBLE_MSB:`MY_DECINFO_FMIS_DOUBLE_LSB

    `define MY_DECINFO_FMIS_WIDTH  (`MY_DECINFO_FMIS_DOUBLE_MSB+1)



    // FMAC group
        `define MY_DECINFO_FMAC_FMADD_LSB   (`MY_DECINFO_FPU_USERM_MSB+1)
        `define MY_DECINFO_FMAC_FMADD_MSB   (`MY_DECINFO_FMAC_FMADD_LSB+1-1)    
    `define MY_DECINFO_FMAC_FMADD   `MY_DECINFO_FMAC_FMADD_MSB:`MY_DECINFO_FMAC_FMADD_LSB 
        `define MY_DECINFO_FMAC_FMSUB_LSB   (`MY_DECINFO_FMAC_FMADD_MSB+1)
        `define MY_DECINFO_FMAC_FMSUB_MSB   (`MY_DECINFO_FMAC_FMSUB_LSB+1-1)    
    `define MY_DECINFO_FMAC_FMSUB   `MY_DECINFO_FMAC_FMSUB_MSB:`MY_DECINFO_FMAC_FMSUB_LSB 
        `define MY_DECINFO_FMAC_FNMSUB_LSB  (`MY_DECINFO_FMAC_FMSUB_MSB+1)
        `define MY_DECINFO_FMAC_FNMSUB_MSB   (`MY_DECINFO_FMAC_FNMSUB_LSB+1-1)    
    `define MY_DECINFO_FMAC_FNMSUB  `MY_DECINFO_FMAC_FNMSUB_MSB:`MY_DECINFO_FMAC_FNMSUB_LSB
        `define MY_DECINFO_FMAC_FNMADD_LSB  (`MY_DECINFO_FMAC_FNMSUB_MSB+1)
        `define MY_DECINFO_FMAC_FNMADD_MSB   (`MY_DECINFO_FMAC_FNMADD_LSB+1-1)    
    `define MY_DECINFO_FMAC_FNMADD  `MY_DECINFO_FMAC_FNMADD_MSB:`MY_DECINFO_FMAC_FNMADD_LSB
        `define MY_DECINFO_FMAC_FADD_LSB  (`MY_DECINFO_FMAC_FNMADD_MSB+1)
        `define MY_DECINFO_FMAC_FADD_MSB   (`MY_DECINFO_FMAC_FADD_LSB+1-1)    
    `define MY_DECINFO_FMAC_FADD  `MY_DECINFO_FMAC_FADD_MSB:`MY_DECINFO_FMAC_FADD_LSB
        `define MY_DECINFO_FMAC_FSUB_LSB  (`MY_DECINFO_FMAC_FADD_MSB+1)
        `define MY_DECINFO_FMAC_FSUB_MSB   (`MY_DECINFO_FMAC_FSUB_LSB+1-1)    
    `define MY_DECINFO_FMAC_FSUB  `MY_DECINFO_FMAC_FSUB_MSB:`MY_DECINFO_FMAC_FSUB_LSB
        `define MY_DECINFO_FMAC_FMUL_LSB  (`MY_DECINFO_FMAC_FSUB_MSB+1)
        `define MY_DECINFO_FMAC_FMUL_MSB   (`MY_DECINFO_FMAC_FMUL_LSB+1-1)    
    `define MY_DECINFO_FMAC_FMUL  `MY_DECINFO_FMAC_FMUL_MSB:`MY_DECINFO_FMAC_FMUL_LSB
        `define MY_DECINFO_FMAC_FMIN_LSB  (`MY_DECINFO_FMAC_FMUL_MSB+1)
        `define MY_DECINFO_FMAC_FMIN_MSB   (`MY_DECINFO_FMAC_FMIN_LSB+1-1)    
    `define MY_DECINFO_FMAC_FMIN  `MY_DECINFO_FMAC_FMIN_MSB:`MY_DECINFO_FMAC_FMIN_LSB
        `define MY_DECINFO_FMAC_FMAX_LSB  (`MY_DECINFO_FMAC_FMIN_MSB+1)
        `define MY_DECINFO_FMAC_FMAX_MSB   (`MY_DECINFO_FMAC_FMAX_LSB+1-1)    
    `define MY_DECINFO_FMAC_FMAX  `MY_DECINFO_FMAC_FMAX_MSB:`MY_DECINFO_FMAC_FMAX_LSB
        `define MY_DECINFO_FMAC_FEQ_LSB  (`MY_DECINFO_FMAC_FMAX_MSB+1)
        `define MY_DECINFO_FMAC_FEQ_MSB   (`MY_DECINFO_FMAC_FEQ_LSB+1-1)    
    `define MY_DECINFO_FMAC_FEQ  `MY_DECINFO_FMAC_FEQ_MSB:`MY_DECINFO_FMAC_FEQ_LSB
        `define MY_DECINFO_FMAC_FLT_LSB  (`MY_DECINFO_FMAC_FEQ_MSB+1)
        `define MY_DECINFO_FMAC_FLT_MSB   (`MY_DECINFO_FMAC_FLT_LSB+1-1)    
    `define MY_DECINFO_FMAC_FLT  `MY_DECINFO_FMAC_FLT_MSB:`MY_DECINFO_FMAC_FLT_LSB
        `define MY_DECINFO_FMAC_FLE_LSB  (`MY_DECINFO_FMAC_FLT_MSB+1)
        `define MY_DECINFO_FMAC_FLE_MSB   (`MY_DECINFO_FMAC_FLE_LSB+1-1)    
    `define MY_DECINFO_FMAC_FLE  `MY_DECINFO_FMAC_FLE_MSB:`MY_DECINFO_FMAC_FLE_LSB
        `define MY_DECINFO_FMAC_DOUBLE_LSB  (`MY_DECINFO_FMAC_FLE_MSB+1)
        `define MY_DECINFO_FMAC_DOUBLE_MSB   (`MY_DECINFO_FMAC_DOUBLE_LSB+1-1)    
    `define MY_DECINFO_FMAC_DOUBLE  `MY_DECINFO_FMAC_DOUBLE_MSB:`MY_DECINFO_FMAC_DOUBLE_LSB

    `define MY_DECINFO_FMAC_WIDTH  (`MY_DECINFO_FMAC_DOUBLE_MSB+1)

    // MULDIV group
        `define MY_DECINFO_MULDIV_RESW_LSB `MY_DECINFO_SUBDECINFO_LSB
        `define MY_DECINFO_MULDIV_RESW_MSB (`MY_DECINFO_MULDIV_RESW_LSB+1-1)
    `define MY_DECINFO_MULDIV_RESW         `MY_DECINFO_MULDIV_RESW_MSB : `MY_DECINFO_MULDIV_RESW_LSB

        // `define MY_DECINFO_MULDIV_MUL_LSB   `MY_DECINFO_SUBDECINFO_LSB
        `define MY_DECINFO_MULDIV_MUL_LSB   (`MY_DECINFO_MULDIV_RESW_MSB+1)
        `define MY_DECINFO_MULDIV_MUL_MSB   (`MY_DECINFO_MULDIV_MUL_LSB+1-1)    
    `define MY_DECINFO_MULDIV_MUL   `MY_DECINFO_MULDIV_MUL_MSB:`MY_DECINFO_MULDIV_MUL_LSB    
        `define MY_DECINFO_MULDIV_MULH_LSB   (`MY_DECINFO_MULDIV_MUL_MSB+1)
        `define MY_DECINFO_MULDIV_MULH_MSB   (`MY_DECINFO_MULDIV_MULH_LSB+1-1)    
    `define MY_DECINFO_MULDIV_MULH   `MY_DECINFO_MULDIV_MULH_MSB:`MY_DECINFO_MULDIV_MULH_LSB 
        `define MY_DECINFO_MULDIV_MULHSU_LSB   (`MY_DECINFO_MULDIV_MULH_MSB+1)
        `define MY_DECINFO_MULDIV_MULHSU_MSB   (`MY_DECINFO_MULDIV_MULHSU_LSB+1-1)    
    `define MY_DECINFO_MULDIV_MULHSU   `MY_DECINFO_MULDIV_MULHSU_MSB:`MY_DECINFO_MULDIV_MULHSU_LSB 
        `define MY_DECINFO_MULDIV_MULHU_LSB  (`MY_DECINFO_MULDIV_MULHSU_MSB+1)
        `define MY_DECINFO_MULDIV_MULHU_MSB   (`MY_DECINFO_MULDIV_MULHU_LSB+1-1)    
    `define MY_DECINFO_MULDIV_MULHU  `MY_DECINFO_MULDIV_MULHU_MSB:`MY_DECINFO_MULDIV_MULHU_LSB
        `define MY_DECINFO_MULDIV_DIV_LSB   (`MY_DECINFO_MULDIV_MULHU_MSB+1)
        `define MY_DECINFO_MULDIV_DIV_MSB   (`MY_DECINFO_MULDIV_DIV_LSB+1-1)    
    `define MY_DECINFO_MULDIV_DIV   `MY_DECINFO_MULDIV_DIV_MSB:`MY_DECINFO_MULDIV_DIV_LSB 
        `define MY_DECINFO_MULDIV_DIVU_LSB  (`MY_DECINFO_MULDIV_DIV_MSB+1)
        `define MY_DECINFO_MULDIV_DIVU_MSB  (`MY_DECINFO_MULDIV_DIVU_LSB+1-1)    
    `define MY_DECINFO_MULDIV_DIVU  `MY_DECINFO_MULDIV_DIVU_MSB:`MY_DECINFO_MULDIV_DIVU_LSB
        `define MY_DECINFO_MULDIV_REM_LSB   (`MY_DECINFO_MULDIV_DIVU_MSB+1)
        `define MY_DECINFO_MULDIV_REM_MSB   (`MY_DECINFO_MULDIV_REM_LSB+1-1)    
    `define MY_DECINFO_MULDIV_REM   `MY_DECINFO_MULDIV_REM_MSB:`MY_DECINFO_MULDIV_REM_LSB    
        `define MY_DECINFO_MULDIV_REMU_LSB   (`MY_DECINFO_MULDIV_REM_MSB+1)
        `define MY_DECINFO_MULDIV_REMU_MSB   (`MY_DECINFO_MULDIV_REMU_LSB+1-1)    
    `define MY_DECINFO_MULDIV_REMU   `MY_DECINFO_MULDIV_REMU_MSB:`MY_DECINFO_MULDIV_REMU_LSB 
        `define MY_DECINFO_MULDIV_B2B_LSB   (`MY_DECINFO_MULDIV_REMU_MSB+1)
        `define MY_DECINFO_MULDIV_B2B_MSB   (`MY_DECINFO_MULDIV_B2B_LSB+1-1)    
    `define MY_DECINFO_MULDIV_B2B   `MY_DECINFO_MULDIV_B2B_MSB:`MY_DECINFO_MULDIV_B2B_LSB 

    `define MY_DECINFO_MULDIV_WIDTH  (`MY_DECINFO_MULDIV_B2B_MSB+1)

    // Choose the longest group as the final DEC info width
    `define MY_DECINFO_WIDTH  (`MY_DECINFO_NICE_WIDTH+1)

    //r: for old modules!!

    `define E203_DECIINNFO_GRP_AGU      `MY_DECINFO_GRP_AGU
    `define E203_DECINFO_WIDTH          `MY_DECINFO_WIDTH
    `define E203_DECINFO_GRP_ALU        `MY_DECINFO_GRP_ALU
    `define E203_DECINFO_GRP_AGU        `MY_DECINFO_GRP_AGU
    `define E203_DECINFO_GRP_NICE       `MY_DECINFO_GRP_NICE
    `define E203_DECINFO_GRP_BJP        `MY_DECINFO_GRP_BJP
    `define E203_DECINFO_GRP_CSR        `MY_DECINFO_GRP_CSR
    `define E203_DECINFO_GRP_WIDTH      `MY_DECINFO_GRP_WIDTH
    `define E203_DECINFO_GRP_MULDIV     `MY_DECINFO_GRP_MULDIV
