./vsrc_old/rtl/mycore/biu_bridge.v
./vsrc_old/rtl/mycore/bpu.v
./vsrc_old/rtl/mycore/csr.v
./vsrc_old/rtl/mycore/dec.v
./vsrc_old/rtl/mycore/dec2exu.v
./vsrc_old/rtl/mycore/div_m.v
./vsrc_old/rtl/mycore/exu_alu.v
./vsrc_old/rtl/mycore/exu_disp.v
./vsrc_old/rtl/mycore/exu_lsu_splt.v
./vsrc_old/rtl/mycore/exu_lsu.v
./vsrc_old/rtl/mycore/exu_wbck.v
./vsrc_old/rtl/mycore/exu_cordic.v
./vsrc_old/rtl/mycore/cordic_sc.v
./vsrc_old/rtl/mycore/icache.v
./vsrc_old/rtl/mycore/itcm_arbt.v
./vsrc_old/rtl/mycore/itcm_ctrl.v
./vsrc_old/rtl/mycore/jtag_mem_splt.v
./vsrc_old/rtl/mycore/minidec.v
./vsrc_old/rtl/mycore/oitf_fifo.v
./vsrc_old/rtl/mycore/pc_reg_m.v
./vsrc_old/rtl/mycore/pc2dec.v
./vsrc_old/rtl/mycore/pipe_ctrl.v
./vsrc_old/rtl/mycore/ppi_bridge.v
./vsrc_old/rtl/mycore/regfile.v
./vsrc_old/rtl/mycore/splt_mux.v
./vsrc_old/rtl/mycore_com/ifu.v
./vsrc_old/rtl/mycore_com/exu.v
./vsrc_old/rtl/mycore_com/ppi_bus.v
./vsrc_old/rtl/mycore_com/myriscv.v
./vsrc_old/rtl/mydebug/jtag_dm.v
./vsrc_old/rtl/mydebug/jtag_driver.v
./vsrc_old/rtl/mydebug/jtag_top.v
./vsrc_old/rtl/myperips/flash_ex_vir_xilinx.v
./vsrc_old/rtl/myperips/simplegpio.v
./vsrc_old/rtl/utils/full_handshake_rx.v
./vsrc_old/rtl/utils/full_handshake_tx.v
./vsrc_old/rtl/utils/sirv_gnrl_dffs.v
./vsrc_old/rtl/utils/sirv_gnrl_xchecker.v
./vsrc_old/rtl/utils/sirv_gnrl_bufs.v
./vsrc_old/rtl/utils/sirv_gnrl_icbs.v
./vsrc_old/rtl/utils/simplefifo.v
./vsrc_old/rtl/soc/myriscv_soc.v
./vsrc_old/rtl/myperips_old/sram.v
./vsrc_old/tb/pc_tb.sv
